version: 3

tasks:
  build-go:
    desc: Build the plugin
    cmds:
      - go build go/...
  proto:
    desc: Generate protobuf files
    cmds:
      - fd -t f -e proto . proto -x protoc -I proto --go_out=go/protonats --go_opt=paths=source_relative --java_out=java/src/main/protobuf {}
