version: 3

tasks:
  proto:
    desc: Generate protobuf files
    cmds:
      - fd -t f -e proto . proto -x protoc -I proto --go_out=go --go_opt=paths=source_relative --java_out=java/src/main/protobuf {}
